application: oppiaserver
version: 1
runtime: python27
api_version: 1
threadsafe: false

env_variables:
  DJANGO_SETTINGS_MODULE: 'oppiaserver.settings'
  OPPIA_VERSION: '1.2.8'

builtins:
- appstats: on
- deferred: on
- remote_api: on

inbound_services:
- warmup

admin_console:
  pages:
  - name: Oppia Admin Page
    url: /admin

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  secure: always
  http_headers:
    Cache-Control: 'public, max-age=2592000'
    Vary: Accept-Encoding
- url: /images
  static_dir: static/images
  secure: always
  http_headers:
    Cache-Control: 'public, max-age=600'
- url: /static/pages
  static_dir: static/pages
  secure: always
  http_headers:
    Cache-Control: 'public, max-age=600'
- url: /robots.txt
  static_files: static/pages/robots.txt
  upload: static/pages/robots.txt
  secure: always
  http_headers:
    Cache-Control: 'public, max-age=2592000'
    Vary: Accept-Encoding
- url: /scripts
  static_dir: static/scripts
  secure: always
  http_headers:
    Cache-Control: 'no-cache'
- url: /css
  # NB: not minified. TODO(sll): fix.
  static_dir: core/templates/dev/head/css
  secure: always
- url: /third_party/static
  static_dir: third_party/static
  secure: always
  http_headers:
    Cache-Control: 'public, max-age=2592000'
    Vary: Accept-Encoding
- url: /extensions/widgets/(.*)/(.*)/static/(.*)
  static_files: extensions/widgets/\1/\2/static/\3
  upload: extensions/widgets/(.*)/(.*)/static/(.*)
  secure: always
  http_headers:
    Cache-Control: 'no-cache'
- url: /extensions/skins/(.*)/static/(.*)
  static_files: extensions/skins/\1/static/\2
  upload: extensions/skins/(.*)/static/(.*)
  secure: always
  http_headers:
    Cache-Control: 'no-cache'
- url: /mapreduce/pipeline/images
  static_dir: third_party/gae-mapreduce-1.9.0.0/mapreduce/lib/pipeline/ui/images
  secure: always
- url: /mapreduce(/.*)?
  script: mapreduce.main.APP
  login: admin
  secure: always
- url: /mapreduce/worker(/.*)?
  script: mapreduce.main.APP
  login: admin
  secure: always
- url: /cron/.*
  login: admin
  script: main_cron.app
- url: /.*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: '2.6'
- name: webapp2
  version: '2.5.2'
